echoLiveEditor.pushPalette([
    {
        meta: {
            name: 'material',
            title: 'Material'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#000000de', title: 'Black - Default' },
            { value: '#0000008a', title: 'Black - Light' },
            { value: '#00000052', title: 'Black - Lighter' },
            { value: '#00000012', title: 'Black - Lightest' },
            { value: '#ffffff', title: 'White' },
            { value: '#ffffffde', title: 'White - Default' },
            { value: '#ffffff8a', title: 'White - Light' },
            { value: '#ffffff52', title: 'White - Lighter' },
            { value: '#ffffff12', title: 'White - Lightest' },

            { type: 'group', value: 'Dark' },
            { value: '#e53734', title: 'Red - Dark' },
            { value: '#c3185d', title: 'Pink - Dark' },
            { value: '#8c24a8', title: 'Purple - Dark' },
            { value: '#673ab6', title: 'Deep Purple - Dark' },
            { value: '#303fa1', title: 'Indigo - Dark' },
            { value: '#1975d2', title: 'Blue - Dark' },
            { value: '#0287cf', title: 'Light Blue - Dark' },
            { value: '#0097a8', title: 'Cyan - Dark' },
            { value: '#007a6c', title: 'Teal - Dark' },
            { value: '#398e3d', title: 'Green - Dark' },
            { value: '#689f38', title: 'Light Green - Dark' },
            { value: '#b0b52c', title: 'Lime - Dark' },
            { value: '#fbc02d', title: 'Yellow - Dark' },
            { value: '#ffa200', title: 'Amber - Dark' },
            { value: '#fa8900', title: 'Orange - Dark' },
            { value: '#f4511f', title: 'Deep Orange - Dark' },
            { value: '#5d4037', title: 'Brown - Dark' },
            { value: '#616161', title: 'Grey - Dark' },
            { value: '#455a63', title: 'Blue Grey - Dark' },

            { type: 'group', value: 'Default' },
            { value: '#ef5552', title: 'Red' },
            { value: '#e92063', title: 'Pink' },
            { value: '#ab47bd', title: 'Purple' },
            { value: '#7e56c2', title: 'Deep Purple' },
            { value: '#4051b5', title: 'Indigo' },
            { value: '#2094f3', title: 'Blue' },
            { value: '#02a6f2', title: 'Light Blue' },
            { value: '#00bdd6', title: 'Cyan' },
            { value: '#009485', title: 'Teal' },
            { value: '#4cae4f', title: 'Green' },
            { value: '#8bc34b', title: 'Light Green' },
            { value: '#cbdc38', title: 'Lime' },
            { value: '#ffec3d', title: 'Yellow' },
            { value: '#ffc105', title: 'Amber' },
            { value: '#ffa724', title: 'Orange' },
            { value: '#ff6e42', title: 'Deep Orange' },
            { value: '#795649', title: 'Brown' },
            { value: '#757575', title: 'Grey' },
            { value: '#546d78', title: 'Blue Grey' },

            { type: 'group', value: 'Light' },
            { value: '#e57171', title: 'Red - Light' },
            { value: '#ec417a', title: 'Pink - Light' },
            { value: '#bb69c9', title: 'Purple - Light' },
            { value: '#9574cd', title: 'Deep Purple - Light' },
            { value: '#5d6cc0', title: 'Indigo - Light' },
            { value: '#42a5f5', title: 'Blue - Light' },
            { value: '#28b5f6', title: 'Light Blue - Light' },
            { value: '#25c5da', title: 'Cyan - Light' },
            { value: '#26a699', title: 'Teal - Light' },
            { value: '#68bb6c', title: 'Green - Light' },
            { value: '#9ccc66', title: 'Light Green - Light' },
            { value: '#d3e156', title: 'Lime - Light' },
            { value: '#ffee57', title: 'Yellow - Light' },
            { value: '#ffc929', title: 'Amber - Light' },
            { value: '#ffad33', title: 'Orange - Light' },
            { value: '#ff8a66', title: 'Deep Orange - Light' },
            { value: '#8d6e62', title: 'Brown - Light' },
            { value: '#9e9e9e', title: 'Grey - Light' },
            { value: '#607c8a', title: 'Blue Grey - Light' }
        ]
    }, {
        meta: {
            name: 'tailwindcss',
            title: 'Tailwind CSS'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#ffffff', title: 'White' },
            { value: '#64748b', title: 'Slate' },
            { value: '#6b7280', title: 'Gray' },
            { value: '#71717a', title: 'Zinc' },
            { value: '#737373', title: 'Neutral' },
            { value: '#787170', title: 'Stone' },

            { type: 'group', value: 'Color 500' },
            { value: '#f43f5e', title: 'Rose' },
            { value: '#f97316', title: 'Orange' },
            { value: '#f59e0b', title: 'Amber' },
            { value: '#eab308', title: 'Yellow' },
            { value: '#84cc16', title: 'Lime' },
            { value: '#22c55e', title: 'Green' },
            { value: '#10b981', title: 'Emerald' },
            { value: '#14b8a6', title: 'Teal' },
            { value: '#06b6d4', title: 'Cyan' },
            { value: '#0ea5e9', title: 'Sky' },
            { value: '#3b82f6', title: 'Blue' },
            { value: '#6366f1', title: 'Indigo' },
            { value: '#8b5cf6', title: 'Violet' },
            { value: '#a855f7', title: 'Purple' },
            { value: '#d945ef', title: 'Fuchsia' },
            { value: '#ec4899', title: 'Pink' }
        ]
    }, {
        meta: {
            name: 'minecraft',
            title: 'Minecraft'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#0000aa', title: 'Dark Blue' },
            { value: '#00aa00', title: 'Dark Green' },
            { value: '#00aaaa', title: 'Dark Aqua' },
            { value: '#aa0000', title: 'Dark Red' },
            { value: '#aa00aa', title: 'Dark Purple' },
            { value: '#ffaa00', title: 'Gold' },
            { value: '#aaaaaa', title: 'Gray' },
            { value: '#555555', title: 'Dark Gray' },
            { value: '#5555ff', title: 'Blue' },
            { value: '#55ff55', title: 'Green' },
            { value: '#55ffff', title: 'Aqua' },
            { value: '#ff5555', title: 'Red' },
            { value: '#ff55ff', title: 'Light Purple' },
            { value: '#ffff55', title: 'Yellow' },
            { value: '#ffffff', title: 'White' },
        ]
    }
]);