echoLiveEditor.pushPalette([
    {
        meta: {
            name: 'material',
            title: 'Material Design'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#000000de', title: 'Black - Default' },
            { value: '#0000008a', title: 'Black - Light' },
            { value: '#00000052', title: 'Black - Lighter' },
            { value: '#00000012', title: 'Black - Lightest' },
            { value: '#ffffff', title: 'White' },
            { value: '#ffffffde', title: 'White - Default' },
            { value: '#ffffff8a', title: 'White - Light' },
            { value: '#ffffff52', title: 'White - Lighter' },
            { value: '#ffffff12', title: 'White - Lightest' },
            { value: '#e2e4e9', title: 'Gray' },
            { value: '#e2e4e9d1', title: 'Gray - Default' },
            { value: '#e2e4e98f', title: 'Gray - Light' },
            { value: '#e2e4e952', title: 'Gray - Lighter' },
            { value: '#e2e4e91f', title: 'Gray - Lightest' },

            { type: 'group', value: 'Dark' },
            { value: '#e53734', title: 'Red - Dark' },
            { value: '#c3185d', title: 'Pink - Dark' },
            { value: '#8c24a8', title: 'Purple - Dark' },
            { value: '#673ab6', title: 'Deep Purple - Dark' },
            { value: '#303fa1', title: 'Indigo - Dark' },
            { value: '#1975d2', title: 'Blue - Dark' },
            { value: '#0287cf', title: 'Light Blue - Dark' },
            { value: '#0097a8', title: 'Cyan - Dark' },
            { value: '#007a6c', title: 'Teal - Dark' },
            { value: '#398e3d', title: 'Green - Dark' },
            { value: '#689f38', title: 'Light Green - Dark' },
            { value: '#b0b52c', title: 'Lime - Dark' },
            { value: '#fbc02d', title: 'Yellow - Dark' },
            { value: '#ffa200', title: 'Amber - Dark' },
            { value: '#fa8900', title: 'Orange - Dark' },
            { value: '#f4511f', title: 'Deep Orange - Dark' },
            { value: '#5d4037', title: 'Brown - Dark' },
            { value: '#616161', title: 'Grey - Dark' },
            { value: '#455a63', title: 'Blue Grey - Dark' },

            { type: 'group', value: 'Default' },
            { value: '#ef5552', title: 'Red' },
            { value: '#e92063', title: 'Pink' },
            { value: '#ab47bd', title: 'Purple' },
            { value: '#7e56c2', title: 'Deep Purple' },
            { value: '#4051b5', title: 'Indigo' },
            { value: '#2094f3', title: 'Blue' },
            { value: '#02a6f2', title: 'Light Blue' },
            { value: '#00bdd6', title: 'Cyan' },
            { value: '#009485', title: 'Teal' },
            { value: '#4cae4f', title: 'Green' },
            { value: '#8bc34b', title: 'Light Green' },
            { value: '#cbdc38', title: 'Lime' },
            { value: '#ffec3d', title: 'Yellow' },
            { value: '#ffc105', title: 'Amber' },
            { value: '#ffa724', title: 'Orange' },
            { value: '#ff6e42', title: 'Deep Orange' },
            { value: '#795649', title: 'Brown' },
            { value: '#757575', title: 'Grey' },
            { value: '#546d78', title: 'Blue Grey' },

            { type: 'group', value: 'Light' },
            { value: '#e57171', title: 'Red - Light' },
            { value: '#ec417a', title: 'Pink - Light' },
            { value: '#bb69c9', title: 'Purple - Light' },
            { value: '#9574cd', title: 'Deep Purple - Light' },
            { value: '#5d6cc0', title: 'Indigo - Light' },
            { value: '#42a5f5', title: 'Blue - Light' },
            { value: '#28b5f6', title: 'Light Blue - Light' },
            { value: '#25c5da', title: 'Cyan - Light' },
            { value: '#26a699', title: 'Teal - Light' },
            { value: '#68bb6c', title: 'Green - Light' },
            { value: '#9ccc66', title: 'Light Green - Light' },
            { value: '#d3e156', title: 'Lime - Light' },
            { value: '#ffee57', title: 'Yellow - Light' },
            { value: '#ffc929', title: 'Amber - Light' },
            { value: '#ffad33', title: 'Orange - Light' },
            { value: '#ff8a66', title: 'Deep Orange - Light' },
            { value: '#8d6e62', title: 'Brown - Light' },
            { value: '#9e9e9e', title: 'Grey - Light' },
            { value: '#607c8a', title: 'Blue Grey - Light' }
        ]
    }, {
        meta: {
            name: 'tailwindcss',
            title: 'Tailwind CSS'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#ffffff', title: 'White' },
            { value: '#64748b', title: 'Slate' },
            { value: '#6b7280', title: 'Gray' },
            { value: '#71717a', title: 'Zinc' },
            { value: '#737373', title: 'Neutral' },
            { value: '#787170', title: 'Stone' },

            { type: 'group', value: 'Weight 500' },
            { value: '#ef4444', title: 'Red 500' },
            { value: '#f97316', title: 'Orange 500' },
            { value: '#f59e0b', title: 'Amber 500' },
            { value: '#eab308', title: 'Yellow 500' },
            { value: '#84cc16', title: 'Lime 500' },
            { value: '#22c55e', title: 'Green 500' },
            { value: '#10b981', title: 'Emerald 500' },
            { value: '#14b8a6', title: 'Teal 500' },
            { value: '#06b6d4', title: 'Cyan 500' },
            { value: '#0ea5e9', title: 'Sky 500' },
            { value: '#3b82f6', title: 'Blue 500' },
            { value: '#6366f1', title: 'Indigo 500' },
            { value: '#8b5cf6', title: 'Violet 500' },
            { value: '#a855f7', title: 'Purple 500' },
            { value: '#d945ef', title: 'Fuchsia 500' },
            { value: '#ec4899', title: 'Pink 500' },
            { value: '#f43f5e', title: 'Rose 500' },

            { type: 'group', value: 'Weight 700' },
            { value: '#b91c1c', title: 'Red 700' },
            { value: '#c2410c', title: 'Orange 700' },
            { value: '#b45309', title: 'Amber 700' },
            { value: '#a16007', title: 'Yellow 700' },
            { value: '#4d7c0f', title: 'Lime 700' },
            { value: '#15803d', title: 'Green 700' },
            { value: '#047857', title: 'Emerald 700' },
            { value: '#0f766e', title: 'Teal 700' },
            { value: '#0e7490', title: 'Cyan 700' },
            { value: '#03719f', title: 'Sky 700' },
            { value: '#1d4ed8', title: 'Blue 700' },
            { value: '#4338ca', title: 'Indigo 700' },
            { value: '#6d28d9', title: 'Violet 700' },
            { value: '#7e22ce', title: 'Purple 700' },
            { value: '#a21caf', title: 'Fuchsia 700' },
            { value: '#be185d', title: 'Pink 700' },
            { value: '#be123c', title: 'Rose 700' },

            { type: 'group', value: 'Weight 300' },
            { value: '#fca5a5', title: 'Red 300' },
            { value: '#fdba74', title: 'Orange 300' },
            { value: '#fcd34d', title: 'Amber 300' },
            { value: '#fde047', title: 'Yellow 300' },
            { value: '#bee664', title: 'Lime 300' },
            { value: '#86efac', title: 'Green 300' },
            { value: '#6ee7b7', title: 'Emerald 300' },
            { value: '#5eeaD4', title: 'Teal 300' },
            { value: '#67e8f9', title: 'Cyan 300' },
            { value: '#7dd3fc', title: 'Sky 300' },
            { value: '#93c5fd', title: 'Blue 300' },
            { value: '#a5b4fc', title: 'Indigo 300' },
            { value: '#c4b5fd', title: 'Violet 300' },
            { value: '#d8b4fe', title: 'Purple 300' },
            { value: '#f0abfc', title: 'Fuchsia 300' },
            { value: '#f9a8d4', title: 'Pink 300' },
            { value: '#fda4af', title: 'Rose 300' }
        ]
    }, {
        meta: {
            name: 'ant_design',
            title: 'Ant Design'
        },
        colors: [
            { value: '#ffffff', title: 'Gray 1' },
            { value: '#fafafa', title: 'Gray 2' },
            { value: '#f5f5f5', title: 'Gray 3' },
            { value: '#f0f0f0', title: 'Gray 4' },
            { value: '#d9d9d9', title: 'Gray 5' },
            { value: '#bfbfbf', title: 'Gray 6' },
            { value: '#8c8c8c', title: 'Gray 7' },
            { value: '#595959', title: 'Gray 8' },
            { value: '#434343', title: 'Gray 9' },
            { value: '#262626', title: 'Gray 10' },
            { value: '#1f1f1f', title: 'Gray 11' },
            { value: '#141414', title: 'Gray 12' },
            { value: '#000000', title: 'Gray 13' },

            { type: 'group', value: '功能色' },
            { value: '#1890ff', title: 'Link' },
            { value: '#25c41a', title: 'Success' },
            { value: '#ffad14', title: 'Warning' },
            { value: '#ff4d4f', title: 'Error' },
            { value: '#177ddc', title: 'Link - Dark' },
            { value: '#49aa19', title: 'Success - Dark' },
            { value: '#d89614', title: 'Warning - Dark' },
            { value: '#a61d24', title: 'Error - Dark' },

            { type: 'group', value: 'Dust Red / 薄暮' },
            { value: '#fff1f0', title: 'Red 1' },
            { value: '#ffccc7', title: 'Red 2' },
            { value: '#ffa39e', title: 'Red 3' },
            { value: '#ff7875', title: 'Red 4' },
            { value: '#ff4d4f', title: 'Red 5' },
            { value: '#f5222d', title: 'Red 6' },
            { value: '#cf1322', title: 'Red 7' },
            { value: '#a8071a', title: 'Red 8' },
            { value: '#820014', title: 'Red 9' },
            { value: '#5c0011', title: 'Red 10' },

            { type: 'group', value: 'Volcano / 火山' },
            { value: '#fff2e8', title: 'Volcano 1' },
            { value: '#ffd8bf', title: 'Volcano 2' },
            { value: '#ffbb96', title: 'Volcano 3' },
            { value: '#ff9c6e', title: 'Volcano 4' },
            { value: '#ff7a45', title: 'Volcano 5' },
            { value: '#fa541c', title: 'Volcano 6' },
            { value: '#d4380d', title: 'Volcano 7' },
            { value: '#ad2102', title: 'Volcano 8' },
            { value: '#871400', title: 'Volcano 9' },
            { value: '#610b00', title: 'Volcano 10' },

            { type: 'group', value: 'Sunset Orange / 日暮' },
            { value: '#fff7e6', title: 'Orange 1' },
            { value: '#ffe7ba', title: 'Orange 2' },
            { value: '#ffd591', title: 'Orange 3' },
            { value: '#ffc069', title: 'Orange 4' },
            { value: '#ffa940', title: 'Orange 5' },
            { value: '#fa8c16', title: 'Orange 6' },
            { value: '#d46b08', title: 'Orange 7' },
            { value: '#ad4e00', title: 'Orange 8' },
            { value: '#873800', title: 'Orange 9' },
            { value: '#612500', title: 'Orange 10' },

            { type: 'group', value: 'Calendula Gold / 金盏花' },
            { value: '#fffbe6', title: 'Gold 1' },
            { value: '#fff1b8', title: 'Gold 2' },
            { value: '#ffe58f', title: 'Gold 3' },
            { value: '#ffd666', title: 'Gold 4' },
            { value: '#ffc53d', title: 'Gold 5' },
            { value: '#faad14', title: 'Gold 6' },
            { value: '#d48806', title: 'Gold 7' },
            { value: '#ad6800', title: 'Gold 8' },
            { value: '#874d00', title: 'Gold 9' },
            { value: '#613400', title: 'Gold 10' },

            { type: 'group', value: 'Sunrise Yellow / 日出' },
            { value: '#feffe6', title: 'Yellow 1' },
            { value: '#ffffb8', title: 'Yellow 2' },
            { value: '#fffb8f', title: 'Yellow 3' },
            { value: '#fff566', title: 'Yellow 4' },
            { value: '#ffec3d', title: 'Yellow 5' },
            { value: '#fadb14', title: 'Yellow 6' },
            { value: '#d4b106', title: 'Yellow 7' },
            { value: '#ad8b00', title: 'Yellow 8' },
            { value: '#876800', title: 'Yellow 9' },
            { value: '#614700', title: 'Yellow 10' },

            { type: 'group', value: 'Lime / 青柠' },
            { value: '#fcffe6', title: 'Lime 1' },
            { value: '#f4ffb8', title: 'Lime 2' },
            { value: '#eaff8f', title: 'Lime 3' },
            { value: '#d3f261', title: 'Lime 4' },
            { value: '#bae637', title: 'Lime 5' },
            { value: '#a0d911', title: 'Lime 6' },
            { value: '#7cb305', title: 'Lime 7' },
            { value: '#5b8c00', title: 'Lime 8' },
            { value: '#3f6600', title: 'Lime 9' },
            { value: '#254000', title: 'Lime 10' },

            { type: 'group', value: 'Polar Green / 极光绿' },
            { value: '#f6ffed', title: 'Green 1' },
            { value: '#d9f7be', title: 'Green 2' },
            { value: '#b7eb8f', title: 'Green 3' },
            { value: '#95de64', title: 'Green 4' },
            { value: '#73d13d', title: 'Green 5' },
            { value: '#52c41a', title: 'Green 6' },
            { value: '#389e0d', title: 'Green 7' },
            { value: '#237804', title: 'Green 8' },
            { value: '#135200', title: 'Green 9' },
            { value: '#092b00', title: 'Green 10' },

            { type: 'group', value: 'Cyan / 明青' },
            { value: '#e6fffb', title: 'Cyan 1' },
            { value: '#b5f5ec', title: 'Cyan 2' },
            { value: '#87e8de', title: 'Cyan 3' },
            { value: '#5cdbd3', title: 'Cyan 4' },
            { value: '#36cfc9', title: 'Cyan 5' },
            { value: '#13c2c2', title: 'Cyan 6' },
            { value: '#08979c', title: 'Cyan 7' },
            { value: '#006d75', title: 'Cyan 8' },
            { value: '#00474f', title: 'Cyan 9' },
            { value: '#002329', title: 'Cyan 10' },

            { type: 'group', value: 'Daybreak Blue / 拂晓蓝' },
            { value: '#e6f4ff', title: 'Blue 1' },
            { value: '#bae0ff', title: 'Blue 2' },
            { value: '#91caff', title: 'Blue 3' },
            { value: '#69b1ff', title: 'Blue 4' },
            { value: '#4096ff', title: 'Blue 5' },
            { value: '#1677ff', title: 'Blue 6' },
            { value: '#0958d9', title: 'Blue 7' },
            { value: '#003eb3', title: 'Blue 8' },
            { value: '#002c8c', title: 'Blue 9' },
            { value: '#001d66', title: 'Blue 10' },

            { type: 'group', value: 'Geek Blue / 极客蓝' },
            { value: '#f0f5ff', title: 'Geek Blue 1' },
            { value: '#d6e4ff', title: 'Geek Blue 2' },
            { value: '#adc6ff', title: 'Geek Blue 3' },
            { value: '#85a5ff', title: 'Geek Blue 4' },
            { value: '#597ef7', title: 'Geek Blue 5' },
            { value: '#2f54eb', title: 'Geek Blue 6' },
            { value: '#1d39c4', title: 'Geek Blue 7' },
            { value: '#10239e', title: 'Geek Blue 8' },
            { value: '#061178', title: 'Geek Blue 9' },
            { value: '#030852', title: 'Geek Blue 10' },

            { type: 'group', value: 'Golden Purple / 酱紫' },
            { value: '#f9f0ff', title: 'Purple 1' },
            { value: '#efdbff', title: 'Purple 2' },
            { value: '#d3adf7', title: 'Purple 3' },
            { value: '#b37feb', title: 'Purple 4' },
            { value: '#9254de', title: 'Purple 5' },
            { value: '#722ed1', title: 'Purple 6' },
            { value: '#531dab', title: 'Purple 7' },
            { value: '#391085', title: 'Purple 8' },
            { value: '#22075e', title: 'Purple 9' },
            { value: '#120338', title: 'Purple 10' },

            { type: 'group', value: 'Magenta / 法式洋红' },
            { value: '#fff0f6', title: 'Magenta 1' },
            { value: '#ffd6e7', title: 'Magenta 2' },
            { value: '#ffadd2', title: 'Magenta 3' },
            { value: '#ff85c0', title: 'Magenta 4' },
            { value: '#f759ab', title: 'Magenta 5' },
            { value: '#eb2f96', title: 'Magenta 6' },
            { value: '#c41d7f', title: 'Magenta 7' },
            { value: '#9e1068', title: 'Magenta 8' },
            { value: '#780650', title: 'Magenta 9' },
            { value: '#520339', title: 'Magenta 10' },
        ]
    }, {
        meta: {
            name: 'minecraft',
            title: 'Minecraft'
        },
        colors: [
            { value: '#000000', title: 'Black' },
            { value: '#0000aa', title: 'Dark Blue' },
            { value: '#00aa00', title: 'Dark Green' },
            { value: '#00aaaa', title: 'Dark Aqua' },
            { value: '#aa0000', title: 'Dark Red' },
            { value: '#aa00aa', title: 'Dark Purple' },
            { value: '#ffaa00', title: 'Gold' },
            { value: '#aaaaaa', title: 'Gray' },
            { value: '#555555', title: 'Dark Gray' },
            { value: '#5555ff', title: 'Blue' },
            { value: '#55ff55', title: 'Green' },
            { value: '#55ffff', title: 'Aqua' },
            { value: '#ff5555', title: 'Red' },
            { value: '#ff55ff', title: 'Light Purple' },
            { value: '#ffff55', title: 'Yellow' },
            { value: '#ffffff', title: 'White' },
        ]
    }
]);